CREATE TABLE [dbo].[RiskInformation] (
    [Id]                       UNIQUEIDENTIFIER CONSTRAINT [DF_RiskInformation_Id] DEFAULT (newsequentialid()) NOT NULL,
    [ProjectDetailsId]         UNIQUEIDENTIFIER NOT NULL,
    [RiskId]                   INT              NULL,
    [Type]                     VARCHAR (100)    NULL,
    [SubType]                  VARCHAR (100)    NULL,
    [IdentifiedDate]           DATETIME         NULL,
    [Description]              VARCHAR (MAX)    NULL,
    [Vulnerability]            VARCHAR (MAX)    NULL,
    [RiskSource]               VARCHAR (250)    NULL,
    [ImpactedAreas]            VARCHAR (MAX)    NULL,
    [InformationAssetImpacted] VARCHAR (1000)   NULL,
    [ExistingControl]          VARCHAR (MAX)    NULL,
    [Location]                 VARCHAR (500)    NULL,
    [Status]                   VARCHAR (50)     NULL,
    [AnalysisProbability]      INT              NULL,
    [AnalysisImpact]           INT              NULL,
    [RiskRating]               VARCHAR (50)     NULL,
    [RiskResponse]             VARCHAR (50)     NULL,
    [NewControls]              VARCHAR (500)    NULL,
    [ContingencyPlan]          VARCHAR (MAX)    NULL,
    [MitigationPlan]           VARCHAR (MAX)    NULL,
    [RelatedPolicy]            VARCHAR (200)    NULL,
    [RTP]                      VARCHAR (100)    NULL,
    [OccurrenceCount]          INT              NULL,
    [ReviewProbability]        INT              NULL,
    [ReviewImpact]             INT              NULL,
    [ReviewRating]             VARCHAR (50)     NULL,
    [Remarks]                  VARCHAR (MAX)    NULL,
    [TargetClosuerDate]        DATETIME         NULL,
    [UpdatedDate]              DATETIME         NULL,
    [IsEmailSend]              BIT              NULL,
    [RiskStatus]               VARCHAR (100)    NULL,
    CONSTRAINT [PK_RiskInformation] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_RiskInformation_ProjectDetailsId] FOREIGN KEY ([ProjectDetailsId]) REFERENCES [dbo].[ProjectDetails] ([Id])
);

