const loginAuthentication = {
  authenticatedusers: null,
  authenticatedHeader: null,
  apiError: false,
  otpauthenticatedusers: null,
  globalvalues: null,
  auth0Token: null,
  isAuthenticated: null,
  decryptRegistrationLinkValue: null,
  registerUserMail: null,
  forgotPassword: null,
  sendunlockcode: null,
  resetAccount: null,
  appConfiguration: null,
  resendOTP: null,
  validateTaxId: null,
  regLinkInfo: null,
  verifyCellPhone: null,
  cellPhoneAuth: null,
  registerInfo: null,
  userPrivilege: {},
  termsGlobalValue: null,
  helpFilePath: null,
  updateRoute: null,
  usersData: {},
  loading: false,
  error: false,
  logout: false,
};
const getBorrower = {
  usersData: {},
  loading: false,
  error: false,
  borrowerLoans: null,
  borrowerSummary: null,
  borrowerActivities: null,
  borrowerStatements: null,
  borrowerRelationship: null,
  borrowerChecklist: null,
};

export default {
  loginAuthentication,
  getBorrower,
};
