export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_CLEAR_SUCCESS = 'POST_LOGIN_CLEAR_SUCCESS';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';

export const GET_RISK = 'GET_RISK';
export const GET_RISK_SUCCESS = 'GET_RISK_SUCCESS';
export const GET_RISK_ERROR = 'GET_RISK_ERROR';
export const EMAIL_RISK_SEND = 'EMAIL_RISK_SEND';
export const EMAIL_RISK_SEND_CLEAR = 'EMAIL_RISK_SEND_CLEAR';

export const UPLOAD_RISK_FILE = 'UPLOAD_RISK_FILE';
export const UPLOAD_RISK_FILE_SUCCESS = 'UPLOAD_RISK_FILE_SUCCESS';
export const UPLOAD_RISK_FILE_CLEAR = 'UPLOAD_RISK_FILE_CLEAR';
export const UPLOAD_RISK_FILE_ERROR = 'UPLOAD_RISK_FILE_ERROR';
export const GET_RISK_FILEINFO = 'GET_RISK_FILEINFO';

export const GET_TODO = 'GET_TODO';
export const GET_TODO_ADD = 'GET_TODO_ADD';
export const GET_TODO_SUCCESS = 'GET_TODO_SUCCESS';
export const GET_TODO_ERROR = 'GET_TODO_ERROR';
export const GET_TODO_DELETED = 'GET_TODO_DELETED';

export const LOG_OUT = 'LOG_OUT';